### PR TITLE
Remove build/nuget/publish-preview-package.yml

### PR DESCRIPTION
**Pull request by tomkerkhove**
Remove `build/nuget/publish-preview-package.yml` as it has been moved to `nuget/publish-preview-package.yml`.

Follow-up for https://github.com/arcus-azure/arcus.security/pull/99

### CODE REVIEW

**Comment by stijnmoreels** [comment]
Before we merge this, you're sure that we use in every YAML build the file in the 'build/nuget' package?

**Comment by tomkerkhove** [comment]
Not yet no, but working through the PRs to get rid of them as we speak!

**Comment by tomkerkhove** [comment]
All of them should now be open and linked to this PR.

https://github.com/search?q=org%3Aarcus-azure+publish-preview-package.yml&type=Code

**Comment by tomkerkhove** [comment]
We're good to go!

**Review by stijnmoreels — APPROVED** [review]

**Pull request merged**
