### PR TITLE
fix: add current version to individual ci build

### LINKED ISSUE #221: Package version ranges cause problems
The version ranges that are specified on package dependencies cause problems when you're experimenting with (MyGet) preview versions

image

### PR DESCRIPTION
**Pull request by stijnmoreels**
Adds current package version to individual CI build for NuGet packages.

Closes https://github.com/arcus-azure/arcus/issues/221

### CODE REVIEW

**Review by pim-simons — APPROVED** [review]
Went through the changes and it looks good to me, but honestly don't really know how to test this 🙈

**Review by fgheysels — APPROVED** [review]

**Comment by fgheysels** [comment]
I believe we'll need the same approach in all repositories ?  (If so, then this PR should not close the related issue)

**Comment by stijnmoreels** [comment]
> I believe we'll need the same approach in all repositories ? (If so, then this PR should not close the related issue)

This is the template repo, changes here will affect all repositories, as all the YAML builds re-use templates that are described here. So, yes, these changes are enough to close the issue.

**Comment by stijnmoreels** [comment]
> Went through the changes and it looks good to me, but honestly don't really know how to test this 🙈

There is a sample project that runs the basic CI build and also runs a release build (without a NuGet release but with a GitHub release) so it gets tested during PR's. You can look at the build logs to see how it works.
See: https://dev.azure.com/codit/Arcus/_build/results?buildId=62202&view=logs&j=143eea66-4597-539b-c2e7-6e457837a569&t=d81092f9-dd49-5d16-29f4-7af6682a9dcd&l=17

**Pull request merged**
