### PR TITLE
FIX: GitHub pre-release/release condition miss-evaluation

### PR DESCRIPTION
**Pull request by stijnmoreels**
Relates to #29

### CODE REVIEW

**Comment by stijnmoreels** [comment]
After looking at all sorts of ways, I came up with this solution: using a single GitHub release template instead of two.

Because of the unwrapping of variables, we had a problem with the GitHub releases and the conditions that weren't evaluating as expected. This fix will make sure that we don't depend on conditions but that we instead (based on the version) provide the correct inputs for the release task.

**Review by tomkerkhove — DISMISSED** [review]
LGTM, but do we have depending pipelines who use different release notes depending on release?

**Comment by stijnmoreels** [comment]
> LGTM, but do we have depending pipelines who use different release notes depending on release?

I checked the EventGrid repo as example and saw that there wasn't any difference.
We could update the template in the future if we require different release notes. Ok?

**Comment by tomkerkhove** [comment]
Sure thing!

Then I suggest to merge this PR, update all our pipelines and delete the old template after that, ok?

**Review by tomkerkhove — APPROVED** [review]

**Comment by tomkerkhove** [comment]
Kept the issue open to track the deletion @stijnmoreels

**Comment by stijnmoreels** [comment]
> Kept the issue open to track the deletion @stijnmoreels

I made an extra one: #34

**Pull request merged**
